apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: source-code
spec:
  type: git
  params:
    - name: revision
      value: main
    - name: url
      value: "your-git-repo-url"

---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: docker-image
spec:
  type: image
  params:
    - name: url
      value: "your-docker-registry-url"
